export interface ROUTES_TYPES {
  LOGIN: 'LOGIN';
  REGISTER: 'REGISTER';
  ONBOARDING: 'ONBOARDING';
  HOME: 'HOME';
  VIDEO_TAB: 'VIDEO_TAB';
  PROFILE: 'PROFILE';

  //stack
  MAIN_TAB: 'MAIN_TAB';
  AUTHORIZED: 'AUTHORIZED';
  UNAUTHORIZED: 'UNAUTHORIZED';

  //other
  REPORT_ISSUE: 'REPORT_ISSUE';
  ANALYTICS: 'ANALYTICS';

  //
  SUBJECT: 'SUBJECT';
  EXAM: 'EXAM';
  RESULT: 'RESULT';
  LITERATURE: 'LITERATURE';
}

const ROUTES: ROUTES_TYPES = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  ONBOARDING: 'ONBOARDING',
  HOME: 'HOME',
  VIDEO_TAB: 'VIDEO_TAB',
  PROFILE: 'PROFILE',

  //stack
  MAIN_TAB: 'MAIN_TAB',
  AUTHORIZED: 'AUTHORIZED',
  UNAUTHORIZED: 'UNAUTHORIZED',

  //other
  REPORT_ISSUE: 'REPORT_ISSUE',
  ANALYTICS: 'ANALYTICS',
  //SUBJECT
  SUBJECT: 'SUBJECT',
  EXAM: 'EXAM',
  RESULT: 'RESULT',
  LITERATURE: 'LITERATURE',
};

export default ROUTES;
